### ISSUE TITLE
Contact info

### ISSUE THREAD

**Issue by ghost** [AniruddhMohan/aniruddhmohan.github.io#2]
Could you please publish your contact information such as an email address? Thank you.

**Comment by AniruddhMohan** [comment]
Hi @enigma-11 ,
What's this about?
BTW, it is not available for sale etc.

**Comment by ghost** [comment]
Are you using the domain name (aniruddhmohan.com)? I wanted it for my business if you're not using it. Happy to purchase it.

**Comment by AniruddhMohan** [comment]
Sorry, not looking to sell it.
BTW, good investigation skills to locate this!
